echo "Loading bash_profile..."
start=$(perl -mTime::HiRes -e 'printf "%.0f\n", (Time::HiRes::time() * 1000)')

eval "$(/opt/homebrew/bin/brew shellenv)"

for f in ~/.*.env; do
    source $f
done

source ~/.bash.brew
source ~/.bash.aliases
source ~/.bash.functions
source ~/.bash.prompt
source ~/.bash.nvm
source ~/.bash.androidstudio

export BASH_SILENCE_DEPRECATION_WARNING=1

end=$(perl -mTime::HiRes -e 'printf "%.0f\n", (Time::HiRes::time() * 1000)')
echo "Loaded in $(($end - $start))ms"