theme = "ayu_dark"

[editor]
bufferline = "always"
auto-format = true
mouse = false

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.lsp]
display-inlay-hints = true

[keys.insert]
C-s = ["normal_mode", ":w"]

[keys.normal."backspace"]
g = ":sh zellij run -f -- lazygit"
e = ":sh zellij run -f -- env"
